title: "Jerock Kalala"
author: "Jerock Kalala"
description: "Bellevue Universisty"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
show_social: true             # show site description and social links in the footer

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home Page", icon: home}
  - {file: "/assets/Rezjerock.pdf", title: "Resume"}
  - {file: "README.md", title: "About Myself", icon: address-card}
  - {title: "Project", url: "https://github.com/jerockkalala/My_project"}
  - {title: "CV", url: "https://acrobat.adobe.com/link/review?uri=urn:aaid:scds:US:734f6e05-9df8-3a54-932b-2b39033cecf1"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: "Let’s Connect!"}
  - {title: Mail, icon: envelope, url: "mailto:jerockkalala@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/jerockkalala"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/jerock_kalala"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/feed/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>. 
